kelompok = input("Masukkan kelompok: ")
asal_daerah = input("Masukkan asal daerah: ")
jumlah_tim = int(input("Masukkan jumlah tim: "))
print(f"Kelompok: {kelompok}")
print(f"Asal daerah: {asal_daerah}")
print(f"Jumlah tim: {jumlah_tim} orang")